replicaCount: 1

image:
  repository: gitlab/gitlab-ce
  tag: "17.7.7-ce.0"
  pullPolicy: Always  # Ensure Always pull policy is used

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: gitlab.cloudmasa.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  existingClaim: gitlab-pvc

externalPostgresql:
  enabled: true
  host: dev-db.cyxw2mqqud77.us-east-1.rds.amazonaws.com
  port: 5432
  database: mydatabase
  username: dbadmin
  password: ChangeMe123!

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "1"

backups:
  existingClaim: gitlab-backup-pvc
