apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: rds-git
env:
  - name: GITLAB_OMNIBUS_CONFIG
    value: |
      external_url 'http://gitlab.cloudmasa.com';
      gitlab_rails['db_adapter'] = 'postgresql';
      gitlab_rails['db_host'] = 'dev-db.cyxw2mqqud77.us-east-1.rds.amazonaws.com';
      gitlab_rails['db_port'] = 5432;
      gitlab_rails['db_database'] = 'mydatabase';
      gitlab_rails['db_username'] = '{{ .Values.postgresql.username }}';
      gitlab_rails['db_password'] = "$(POSTGRES_PASSWORD)";
      nginx['listen_port'] = 80;
