apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: rds-git
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
        - name: gitlab
          image: "{{ .Values.image.repository }}@sha256:{{ .Values.image.digest }}"
          imagePullPolicy: Always
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.example.com';
                gitlab_rails['db_host'] = '{{ .Values.postgresql.host }}';
                gitlab_rails['db_port'] = {{ .Values.postgresql.port }};
                gitlab_rails['db_database'] = '{{ .Values.postgresql.database }}';
                gitlab_rails['db_username'] = '{{ .Values.postgresql.username }}';
                gitlab_rails['db_password'] = "$(POSTGRES_PASSWORD)";
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.existingSecret }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/opt/gitlab
              name: gitlab-storage
            - mountPath: /var/opt/gitlab/backups
              name: gitlab-backup-volume
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
        - name: gitlab-backup-volume
          persistentVolumeClaim:
            claimName: gitlab-backup-pvc
