apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgres-secret
  namespace: rds-git
type: Opaque
data:
  username: ZGJhZG1pbg==            # dbadmin
  password: Q2hhbmdlTWUxMjMh         # ChangeMe123!
  database: bXlkYXRhYmFzZQ==         # mydatabase
  
