apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgres-secret
  namespace: rds-git
type: Opaque
data:
  host: ZGV2LWRiLmN5eHcybXF1cGR3Lmd1ZGVyY2FzdC5jb20= # base64 encoded PostgreSQL host
  password: Q2hhbmdlTWUxMjMh
  username: ZGJhZG1pbg==
  database: bXlkYXRhYmFzZQ==
